BoxLayout:
    orientation: 'vertical'
    BoxLayout:
        orientation: 'horizontal'
        TextInput:
            id: input_miles
            font_size: 40
        BoxLayout:
            orientation: 'vertical'
            Button:
                text: 'Up'
                font_size: 30
                on_press: app.handle_increment(1)
            Button:
                text: 'Down'
                font_size: 30
                on_press: app.handle_increment(-1)
    Button:
        text: app.message
        font_size: 30
        on_press: app.handle_conversion()
    Label:
        id: output_km
        font_size: 40
        color: (1, 1, 0, 1)